### PR TITLE
issue-111

### PR DESCRIPTION
**Pull request by IgorMaksymov**
На проверку, connect to #111

### CODE REVIEW

**Comment by vaa25** [comment]
@TestExecutionListeners для чего тут?

**Comment by vaa25** [comment]
applicationContextTestAddon.xml и webApplicationContextTestAddon.xml почти одинаковы, нарушение принципа DRY

**Comment by IgorMaksymov** [comment]
ок, что ты можешь предложить, чтобы не нарушать его?
мне надо запустить тесты без dbUnitDatabaseConnection.
предлагаю разнести по нескольким файлам и переделать остальные тесты.

**Comment by vaa25** [comment]
1. GlobalExceptionHandler, EventNotFoundException are redundant
2. Misprint in validUnassignReaon 
3. Why absence of reason is invalid case?
4. shouldNotUnassignAssignUserFromEventIfParamLengthIsNotValid should be divided in two test cases

**Comment by IgorMaksymov** [comment]
@vaa25 
1) where you see GlobalExceptionHandler ?
are you updated branch?
3) why not? we need it so it should not be null
4) ok

**Comment by vaa25** [comment]
@vkuchyn does unassign reason is necessary for us?

**Comment by vkuchyn** [comment]
@vaa25 I think it's not neccessary

**Comment by vaa25** [comment]
@IgorMaksymov can you add test with empty unassign reason&?

**Comment by vaa25** [comment]
+ PASSED

**Comment by vaa25** [comment]
@vkuchyn if it not necessary, how shall we receive its absence in controller and other layers? As null or as empty string?

**Comment by IgorMaksymov** [comment]
@vkuchyn my vision of feature: user just click OK at Controller receives empty string "", but not null.

**Comment by vaa25** [comment]
+ PASSED

**Comment by vkuchyn** [comment]
@vaa25 this branch has conflicts - need to resolve

**Comment by vaa25** [comment]
@vkuchyn really they are, but earlier they weren't

**Comment by vkuchyn** [comment]
@vaa25 I see, that could happens - just kindly ask commiter to fix them. Someone have to do them. Less changes in PR - less probability of conflicts.
The quicker  author make fixes - less probability of conflicts

**Comment by vaa25** [comment]
@IgorMaksymov please resolve conflicts

**Comment by IgorMaksymov** [comment]
@vaa25 fixed
@romach review pls

**Comment by IgorMaksymov** [comment]
@vaa25  @romach  all problems fixed, review pls

**Comment by vaa25** [comment]
Return previous PASSED, because of its illegal removing. Merge quality not reviewed.
+ PASSED

**Comment by romach** [comment]
* PASSED

**Comment by vkuchyn** [comment]
@romach after merge, please inform PM to close ticket

**Comment by IgorMaksymov** [comment]
@vkuchyn who shall assign you to task, after finish?

**Comment by romach** [comment]
@vkuchyn I accidentally close it. Have I to reopen it or I can only inform PM?

**Comment by vkuchyn** [comment]
@IgorMaksymov noone. Need to inform PM to close the task.

**Comment by vkuchyn** [comment]
@romach just inform

**Comment by IgorMaksymov** [comment]
@vkuchyn we dont have such rules in workflow, we need to add them
alse REVIEWER assigns you to the task, rule 3.3.3.3

**Comment by romach** [comment]
@AndriyBaibak time spent: 30m
@AndriyBaibak issue is done

**Comment by vkuchyn** [comment]
@IgorMaksymov ok, thanks - will fix the rules

**Comment by IgorMaksymov** [comment]
github automaticly wired my 3.3.3.3 to workflow! cool!

**Comment by romach** [comment]
@IgorMaksymov no, I did it.

**Pull request merged**
