### PR TITLE
#197 Return JSON error if user hasn't rights

### PR DESCRIPTION
**Pull request by roma-ilnitsky**
Connect to #197 
@AndriyBaibak 3:00

### CODE REVIEW

**Comment by romach** [comment]
@roma-ilnitsky JSON isn't returned if subscriber try to enter to `/admin`

**Comment by romach** [comment]
@AndriyBaibak 30 minutes

**Comment by roma-ilnitsky** [comment]
@romach thanks for review ) I will be fix it )

**Comment by roma-ilnitsky** [comment]
@romach done
@AndriyBaibak 0:30

**Comment by vaa25** [comment]
@roma-ilnitsky All right, but there are some funny [things](https://translate.google.com/#en/uk/massage%2C%20mesage)
@AndriyBaibak 30 min

**Comment by roma-ilnitsky** [comment]
@vaa25 I always confuse these words )

**Comment by vaa25** [comment]
+PASSED
@AndriyBaibak 10 min

**Comment by romach** [comment]
+PASSED
@AndriyBaibak 30 minutes

**Pull request merged**
