### PR TITLE
#169-crawler-architecture

### PR DESCRIPTION
**Pull request by vaa25**
connect to #175
@AndriyBaibak 4 hours

### CODE REVIEW

**Comment by romach** [comment]
@vaa25 why #169 is closed?

**Comment by vaa25** [comment]
@romach what do you mean?

**Comment by romach** [comment]
@vaa25 your pull request is connected to issue #169 but it is closed. Maybe you need to reopen it?

**Comment by vaa25** [comment]
@romach yes, I did mistake with number of issue. Correct number is #175

**Comment by alex-anakin** [comment]
@vaa25 Fix one little thing (see comment) and thats all. Then you can merge branche to master by yourself.

@AndriyBaibak time tracking: 10 minutes spent

**Pull request merged**
