### PR TITLE
#124: reduce count of first-level packages

### PR DESCRIPTION
**Pull request by romach**
connect to #124

### CODE REVIEW

**Comment by roma-ilnitsky** [comment]
Why is security package in the controller package ?

**Comment by IgorMaksymov** [comment]
@roma-ilnitsky bacuse security works with URL's which handled by Controllers, i guess.

**Comment by vaa25** [comment]
Why is security package in the service package ?

**Comment by romach** [comment]
@vaa25 bacause of #116

**Comment by vaa25** [comment]
+ PASSED

**Comment by roma-ilnitsky** [comment]
* **passed**

**Comment by IgorMaksymov** [comment]
i guess, this PR should be reopened and branch restored for test package refactor

**Comment by vkuchyn** [comment]
Please, edit your comments above and put person name to whom you are writing (person nick starts with `@`). Leave this habbit for future
@roma-ilnitsky https://github.com/JuniorsJava/itevents/pull/154#issuecomment-181056569 
@vaa25 https://github.com/JuniorsJava/itevents/pull/154#issuecomment-181073746
@IgorMaksymov https://github.com/JuniorsJava/itevents/pull/154#issuecomment-181572742

**Pull request merged**
