### PR TITLE
#196: fixed ROLE check in security checks

### PR DESCRIPTION
**Pull request by IgorMaksymov**
connect to #196

### CODE REVIEW

**Comment by vaa25** [comment]
@IgorMaksymov 
1. MyBatisUserServiceTest
.shouldAddSubscriber(), .shouldThrowEntityAlreadyExistsServiceExceptionWhenAddExistingSubscriber():
1.1 `userDao` rule has redundant `eq`, `any`
1.2 `guestRole` is created two times (DRY)
2. some methods such `setOtpToUser`shouldn't be public and should be removed from service interface

@AndriyBaibak 20 min

**Comment by IgorMaksymov** [comment]
@vaa25 make new task for this

**Comment by vaa25** [comment]
+ PASSED

**Comment by romach** [comment]
@IgorMaksymov branch name `196-permission-error` doesn't match issue name (`Fix 403 error when enter admin resources (/admin, /users/*/events) with admin user.`) nor pull request name (`#196: fixed ROLE check in security checks`)

**Comment by romach** [comment]
@IgorMaksymov I think that we also need security test for `/users/*/events`

**Comment by romach** [comment]
@AndriyBaibak 30 minutes spent

**Comment by IgorMaksymov** [comment]
@romach  when i was taking this task,i dont knew what exactly is happening, that why different names.
http 403 is permission error, when you dont have enough rights.

**Comment by IgorMaksymov** [comment]
@romach fixed

**Comment by romach** [comment]
@IgorMaksymov you could give the issue name to branch (`#196-fix-403-error-when-enter-admin-resources-with-admin`)

**Comment by romach** [comment]
@IgorMaksymov you should run build locally before pushing to GitHub to avoid fix-commits

**Comment by IgorMaksymov** [comment]
@romach yes, sorry, just woke up

**Pull request merged**
