### PR TITLE
#182: add default json format

### PR DESCRIPTION
**Pull request by roma-ilnitsky**
Fix return format of /events/{id}
@AndriyBaibak 1:00
connect to #182

### CODE REVIEW

**Comment by vaa25** [comment]
@roma-ilnitsky Can you show your fix effectivity by test?

**Comment by roma-ilnitsky** [comment]
@vaa25 No, in task nothing is said about test.

**Comment by vaa25** [comment]
@roma-ilnitsky then I can't give`PASSED` ([1.3.2](https://github.com/JuniorsJava/itevents/wiki/Workflow))

**Comment by roma-ilnitsky** [comment]
@vaa25 done
@AndriyBaibak 1:00

**Comment by romach** [comment]
* PASSED @AndriyBaibak 30 minutes

**Pull request merged**
