### PR TITLE
#125 add period to filter

### PR DESCRIPTION
**Pull request by romach**
connect to #125

### CODE REVIEW

**Comment by vaa25** [comment]
@romach resolve conflicts. please

**Comment by vaa25** [comment]
@romach 
1. FilterConverter: why getDefaultItemsPerPage is separate public method? Is it dead code?
2. FilterWrapperBuilder: it used only in tests, but placed in the production code. Is this correct?
3. DateTimeUtil: static methods still there, and no new issue about it. [discussion](https://juja-itevents.slack.com/archives/questions_fo_meeting/p1456293251000004)
4. FilterConverterTest.java: placed in package `wrapper` instead of `converter`; contains unused import
5. EventMyBatisDaoDbTest uses  static methods of DateTimeUtil, same as 3.
6. EventDateReplacementDataSetLoader: you changed format, but didn't change comment described it. Can you explain why did you change format?

**Comment by romach** [comment]
@vaa25 

> 1) FilterConverter: why getDefaultItemsPerPage is separate public method? Is it dead code?

Yes, but this code is [yours](https://github.com/JuniorsJava/itevents/commit/35c49d2534086e6f1719530bb0cbae0454e3a5fa#diff-52bb0d97a071a3d226c40e4e5b34c31cR54), should I fix it?

> 2) FilterWrapperBuilder: it used only in tests, but placed in the production code. Is this correct?

Will be fixed.

> 3) DateTimeUtil: static methods still there, and no new issue about it.

* new issue will be created.

* `//todo` will be added

> 4) FilterConverterTest.java: placed in package wrapper instead of converter; contains unused import

Will be fixed.

> 5) EventMyBatisDaoDbTest uses static methods of DateTimeUtil, same as 3.

* new issue will be created.

* `//todo` will be added

> 6) EventDateReplacementDataSetLoader: you changed format, but didn't change comment described it. Can you explain why did you change format?

Comment will be fixed. I have changed the format because in [this test](https://github.com/JuniorsJava/itevents/blob/1edfa695a9299d4a611b664bd2981c1d6bf3caf7/restservice/src/test/java/org/itevents/dao/mybatis/mapper/EventMyBatisDaoDbTest.java#L248) I receive current  time from database and set time to expected event in [this method](https://github.com/JuniorsJava/itevents/blob/79de6a810e1c36db7d381f8acfbe78b958717114/restservice/src/test/java/org/itevents/test_utils/BuilderUtil.java#L481-L481). So these times must have the same precision (milliseconds).

**Comment by vaa25** [comment]
@romach 1) yes, please) Its very good if somebody thinks that his halfyear code is bullshit)

**Comment by romach** [comment]
Fixed according to above comments.
@vaa25, @alex-anakin review me, please.

**Comment by vaa25** [comment]
+ PASSED
@AndriyBaibak 10 min

**Comment by alex-anakin** [comment]
@romach 
1. Separate `converters.xml` context is redundant.
2. It isn't necessary to run application context in `FilterConverterTest` if you use mocks. Because running it is a very slow process. But one of the main advantages of the unit test is performance. You can use MockitoJUnitRunner instead SpringJUnit4ClassRunner.
3. I recommend to use self-explaining methods names instead comments (in class `EventDateReplacementDataSetLoader`).

**Comment by alex-anakin** [comment]
@AndriyBaibak time tracking: 20 minutes spent

**Comment by romach** [comment]
@alex-anakin 
> Separate converters.xml context is **redundant**.

`converters.xml` deleted

> It isn't necessary to run application context in FilterConverterTest if you use mocks. Because running it is a very slow process. But one of the main advantages of the unit test is performance. **You can use MockitoJUnitRunner** instead SpringJUnit4ClassRunner.

`MockitoJUnitRunner` is used

> I recommend to use **self-explanatory methods names** instead comments (in class EventDateReplacementDataSetLoader).

`EventDateReplacementDataSetLoader` refactored

**Pull request closed without merging**
