### PR TITLE
#130 return json if authentication is required

### PR DESCRIPTION
**Pull request by romach**
connect to #130

### CODE REVIEW

**Comment by romach** [comment]
@vaa25 , @alex-anakin review me, please

**Comment by vaa25** [comment]
+ PASSED
@AndriyBaibak 1 hour

**Comment by alex-anakin** [comment]
@AndriyBaibak time tracking: 30 minutes

**Comment by romach** [comment]
@alex-anakin above comments fixed

**Comment by alex-anakin** [comment]
almost PASSED

@romach 
Fix grammar mistake in `JsonAuthenticationFailureResponseTest.shouldFillResponseWithDefaultExcepptionInformation()` method name, then merge master to your branch.
After that, you can merge your branch into master by yourself.

**Comment by alex-anakin** [comment]
@AndriyBaibak time tracking: 15 minutes

**Pull request closed without merging**
