### PR TITLE
#172 date time util refactor

### PR DESCRIPTION
**Pull request by romach**
connect to #172

### CODE REVIEW

**Comment by romach** [comment]
@vaa25 , @alex-anakin review me, please

**Comment by vaa25** [comment]
@romach There are some `new Date()` in OneTimePassword, MyBatisEventService, MyBatisUserService
@AndriyBaibak 30 min

**Comment by romach** [comment]
@vaa25 done

**Comment by vaa25** [comment]
+ PASSED

**Comment by alex-anakin** [comment]
@romach 
1. Class `CustomDateTime` is over engineered or badly designed. 
For example, how used one of it' methods:
`Date yesterdayDate = new CustomDateTime()
                .withLocalDateTime(clock.getNowLocalDateTime().minusDays(1))
                .getDate();`
Inside `withLocalDateTime` method there is another `new CustomDateTime(...)`. 

2. Result of `CustomDateTime.getDate()` is very similar to `RealClock.getNowLocalDateTime()`. Can you explain the difference or neccessary of `CustomDateTime.getDate()` existing?

3. Method `CustomDateTime.getLocalDateTime()` is never used.

4. You should use interface that class `CustomDateTime` will implement.

5. Class `RealClock` can be final.

6. Comment over `RealClock.getNowLocalDateTime()` is redundant because method purpose is obvious.

**Comment by alex-anakin** [comment]
@AndriyBaibak time tracking: 30 minutes spent

**Comment by romach** [comment]
@alex-anakin 
1. now `CustomDateTime` is used in `RealClock` and `FrozenClock` to reduce code duplication;
2. fixed in `1.`;
3. `DateTime` interface added;
4. `RealClock` and `FrozenClock` classes was made final;
5. Comment over `RealClock.getNowLocalDateTime` is deleted;
6. I decided to make `CustomDateTime` class immutable. So, I can't use setters to change object's state;

**Comment by alex-anakin** [comment]
@romach 
Concerning class `CustomDateTime`.
`CustomDateTime` breaks the single responsibility principle. It is responsible for getting date values and for creating new instances of the class. Perhaps you should create another class and implement the factory method pattern. Or try find your own way.

**Comment by alex-anakin** [comment]
@AndriyBaibak time tracking: 20 minutes spent

**Comment by alex-anakin** [comment]
testing new labels

**Comment by IgorMaksymov** [comment]
@romach after merging master to this branch, please check TODO in MyBatisUserService

**Comment by romach** [comment]
@alex-anakin `DateTimeFactory` [added](https://github.com/JuniorsJava/itevents/pull/195/commits/40e9c10ad8ca52e682d84b05df7ea2fb869c3b4b), review please

**Pull request closed without merging**
