### PR TITLE
#188: module website removed

### PR DESCRIPTION
**Pull request by IgorMaksymov**
connect to #188

### CODE REVIEW

**Comment by vaa25** [comment]
@IgorMaksymov You forgot about https://github.com/JuniorsJava/itevents/blob/%23188-remove-module-website/settings.gradle

**Comment by IgorMaksymov** [comment]
@vaa25 fixed

**Comment by vaa25** [comment]
+ PASSED
@AndriyBaibak 5 min

**Comment by romach** [comment]
* PASSED

**Pull request merged**
