### PR TITLE
#214=fix-pmd-crawler

### PR DESCRIPTION
**Pull request by vaa25**
connect to #214

### CODE REVIEW

**Comment by vaa25** [comment]
@AndriyBaibak 4 hours

**Comment by romach** [comment]
@vaa25
Build fails with message:
```
:crawler:checkstyleTest                 
[ant:checkstyle] \itevents\crawler\src\test\java\org\itevents\MockTest.java:0: Missing package-info.java file.
[ant:checkstyle] \itevents\crawler\src\test\java\org\itevents\MockTest.java:5: Wrong order for 'org.hamcrest.MatcherAssert.assert
That' import.
[ant:checkstyle] \itevents\crawler\src\test\java\org\itevents\MockTest.java:8: warning: First sentence should end with a period.
:crawler:checkstyleTest FAILED          
              
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':crawler:checkstyleTest'.
```

**Comment by vaa25** [comment]
@romach \itevents\crawler\src\test\java\org\itevents\MockTest.java was deleted earlier. Where did you find it?

**Comment by romach** [comment]
@vaa25 https://github.com/JuniorsJava/itevents/blob/%23214%3Dfix-pmd-crawler/crawler/src/test/java/org/itevents/MockTest.java

**Pull request closed without merging**
